[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "frontend/build"

# SPA fallback so deep links work on reload
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
